---
- name: Check if librenms is already installed
  ansible.builtin.stat:
    path: "{{ librenms_home }}"
  register: __librenms_path

- name: Install librenms
  ansible.builtin.composer:
    command: create-project
    arguments: --keep-vcs librenms/librenms /opt/librenms dev-master
    no_dev: yes
    prefer_dist: yes
    working_dir: /tmp
  become: true
  become_user: "{{ librenms_user }}"
  when: not __librenms_path.stat.exists

- name: Change ownership
  ansible.builtin.file:
    path: "{{ librenms_home }}"
    owner: "{{ librenms_user }}"
    group: "{{ librenms_group }}"
    recurse: true
  tags:
    - ownership

- name: "Apply permissions on {{ librenms_home }}"
  ansible.builtin.file:
    path: "{{ librenms_home }}"
    mode: u=rwX,g=rwX

- name: Set acls
  ansible.builtin.acl:
    default: "{{ item.default | default(false) }}"
    path: "{{ item.path }}"
    permissions: "rwx"
    etype: "group"
    entity: "{{ librenms_group }}"
    recursive: "{{ item.recursive | default(false) }}"
    state: present
  with_items:
    # default rules
    - path: "{{ librenms_home }}/rrd"
      default: true
    - path: "{{ librenms_home }}/logs"
      default: true
    - path: "{{ librenms_home }}/bootstrap/cache/"
      default: true
    - path: "{{ librenms_home }}/storage/"
      default: true
    # apply recursive
    - path: "{{ librenms_home }}/rrd"
      recursive: true
    - path: "{{ librenms_home }}/logs"
      recursive: true
    - path: "{{ librenms_home }}/bootstrap/cache/"
      recursive: true
    - path: "{{ librenms_home }}/storage/"
      recursive: true

- name: Update running daily.sh.  # noqa 301
  ansible.builtin.command: "./daily.sh"
  args:
    chdir: "{{ librenms_home }}"
  become_user: "{{ librenms_user }}"
  become: yes
  tags:
    - migrate
    - daily_sh

- name: Initially set admin user password.  # noqa 301
  ansible.builtin.command: "./lnms user:add --role admin --password={{ librenms_admin_password }} {{ librenms_admin_user }}"
  args:
    chdir: "{{ librenms_home }}"
  become_user: "{{ librenms_user }}"
  become: yes
  register: admin_user_result
  changed_when: not admin_user_result.stdout is search("The username has already been taken")
  failed_when:
    - admin_user_result.rc != 0
    - not admin_user_result.stdout is search("The username has already been taken")
  tags:
    - migrate

- name: Deploy cronjob
  ansible.builtin.copy:
    src: "{{ librenms_home }}/dist/librenms.cron"
    dest: /etc/cron.d/librenms
    remote_src: true
    mode: 0644

- name: Deploy logrotate
  ansible.builtin.copy:
    src: "{{ librenms_home }}/misc/librenms.logrotate"
    dest: /etc/logrotate.d/librenms
    remote_src: true
    mode: 0644
